
'LOKEYULA DATAPORT
#define LOKEYULAI_DATAPORT 129
'LOKEYULA COMMAND PORT
#define LOKEYULAI_COMMANDPORT 131

'LOKEYULA Virtual Function Table
#define LOKEYULAI_CLS 10
#define LOKEYULAI_CLEARBITMAP 11
#define LOKEYULAI_CLEARATTRIBUTES 12

#define LOKEYULAI_PLOT 20
#define LOKEYULAI_LINE 21
#define LOKEYULAI_RECTANGLE 22
#define LOKEYULAI_RECTANGLEFILLED 23
#define LOKEYULAI_TRIANGLE 24
#define LOKEYULAI_TRIANGLEFILLED 25
#define LOKEYULAI_CIRCLE 26
#define LOKEYULAI_CIRCLEFILLED 27

#define LOKEYULAI_SCROLL 140
#define LOKEYULAI_ROLL 141

#define LOKEYULAI_PRINTCHAR 160
#define LOKEYULAI_PRINTLINE 161

'LOKEYULA Text functions
#define LOKEYULAI_COPYROMTOSPRITE 110
#define LOKEYULAI_COPYSPRITETORENDER 111
#define LOKEYULAI_ROMLOASCREENRENDER 112
#define LOKEYULAI_ROMLOASCREENSPRITE 113
#define LOKEYULAI_BLIT 120
#define LOKEYULAI_BLITATTRIBUTE 121

#define LOKEYULAI_SETCOPPERINTENSITY 150
#define LOKEYULAI_SETCOPPERINTENSITYRANGE 151
#define LOKEYULAI_COPPERINTENSITYSHIFT 152
#define LOKEYULAI_COPPERINTENSITYROLL 153
#define LOKEYULAI_SETCOPPERPALETTE 155
#define LOKEYULAI_SETCOPPERPALETTERANGE 156
#define LOKEYULAI_COPPERPALETTESHIFT 157
#define LOKEYULAI_COPPERPALETTEROLL 158

'LOKEYULA BITPATTERNS
#define LOKEYULAI_FILLOVERDRAW %10000000
#define LOKEYULAI_FILLPATTERN %01000000
#define LOKEYULAI_FILLPATTERNINDEXY %00000111
#define LOKEYULAI_FILLPATTERNINDEXX %00111000
#define LOKEYULAI_BLITSOURCESPRITE %00000010
#define LOKEYULAI_BLITDESTSPRITE %00000001

Sub WriteULongToULAZX(value as ULong)
	OUT LOKEYULAI_DATAPORT,PEEK (@value)
	OUT LOKEYULAI_DATAPORT,PEEK (@value+1)
	OUT LOKEYULAI_DATAPORT,PEEK (@value+2)
	OUT LOKEYULAI_DATAPORT,PEEK (@value+3)
end Sub

Function ReadULongFromULAZX() as ULong
	DIM retval as Ulong
	Poke (@retval),IN LOKEYULAI_DATAPORT
	Poke (@retval+1),IN LOKEYULAI_DATAPORT
	Poke (@retval+2),IN LOKEYULAI_DATAPORT
	Poke (@retval+3),IN LOKEYULAI_DATAPORT
	return retval
end Function

Sub WriteUIntegerToULAZX(value as UInteger)
	'push UINTEGER ULAZX
	OUT LOKEYULAI_DATAPORT,PEEK (@value)
	OUT LOKEYULAI_DATAPORT,PEEK (@value+1)
end Sub

sub LOKEYULA_Cls()
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_CLS
end sub

sub LOKEYULA_Plot(x as UBYTE,y as UBYTE)
	OUT LOKEYULAI_DATAPORT,x
	OUT LOKEYULAI_DATAPORT,y
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_PLOT
end sub

sub LOKEYULA_Line(x1 as UBYTE,y1 as UBYTE, x2 as UBYTE,y2 as UBYTE)
	OUT LOKEYULAI_DATAPORT,x1
	OUT LOKEYULAI_DATAPORT,y1
	OUT LOKEYULAI_DATAPORT,x2
	OUT LOKEYULAI_DATAPORT,y2
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_LINE
end sub

sub LOKEYULA_Rectangle(x1 as UBYTE,y1 as UBYTE, x2 as UBYTE,y2 as UBYTE)
	OUT LOKEYULAI_DATAPORT,x1
	OUT LOKEYULAI_DATAPORT,y1
	OUT LOKEYULAI_DATAPORT,x2
	OUT LOKEYULAI_DATAPORT,y2
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_RECTANGLE
end sub
sub LOKEYULA_RectangleFilled(x1 as UBYTE,y1 as UBYTE, x2 as UBYTE,y2 as UBYTE,fillpattern as UBYTE)
	OUT LOKEYULAI_DATAPORT,x1
	OUT LOKEYULAI_DATAPORT,y1
	OUT LOKEYULAI_DATAPORT,x2
	OUT LOKEYULAI_DATAPORT,y2
	OUT LOKEYULAI_DATAPORT,fillpattern
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_RECTANGLEFILLED
end sub

sub LOKEYULA_Circle(x as UBYTE,y as UBYTE, r as UBYTE)
	OUT LOKEYULAI_DATAPORT,x
	OUT LOKEYULAI_DATAPORT,y
	OUT LOKEYULAI_DATAPORT,r
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_CIRCLE
end sub
sub LOKEYULA_CircleFilled(x as UBYTE,y as UBYTE, r as UBYTE,fillpattern as UBYTE)
	OUT LOKEYULAI_DATAPORT,x
	OUT LOKEYULAI_DATAPORT,y
	OUT LOKEYULAI_DATAPORT,r
	OUT LOKEYULAI_DATAPORT,fillpattern
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_CIRCLEFILLED
end sub

sub LOKEYULA_Triangle(x1 as UBYTE,y1 as UBYTE,x2 as UBYTE,y2 as UBYTE, x3 as UBYTE, y3 as UBYTE)
	OUT LOKEYULAI_DATAPORT,x1
	OUT LOKEYULAI_DATAPORT,y1
	OUT LOKEYULAI_DATAPORT,x2
	OUT LOKEYULAI_DATAPORT,y2
	OUT LOKEYULAI_DATAPORT,x3
	OUT LOKEYULAI_DATAPORT,y3
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_TRIANGLE
end sub
sub LOKEYULA_TriangleFilled(x1 as UBYTE,y1 as UBYTE,x2 as UBYTE,y2 as UBYTE, x3 as UBYTE, y3 as UBYTE,fillpattern as UBYTE)
	OUT LOKEYULAI_DATAPORT,x1
	OUT LOKEYULAI_DATAPORT,y1
	OUT LOKEYULAI_DATAPORT,x2
	OUT LOKEYULAI_DATAPORT,y2
	OUT LOKEYULAI_DATAPORT,x3
	OUT LOKEYULAI_DATAPORT,y3
	OUT LOKEYULAI_DATAPORT,fillpattern
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_TRIANGLEFILLED
end sub

sub LOKEYULA_CopyROMToSprite(bank as UBYTE, slice as UBYTE)
	OUT LOKEYULAI_DATAPORT,bank
	OUT LOKEYULAI_DATAPORT,slice
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_COPYROMTOSPRITE
end sub

sub LOKEYULA_CopySpriteToRender()
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_COPYSPRITETORENDER
end sub

sub LOKEYULA_Scroll(direction as UBYTE, numpixels as UBYTE,scrollattributes as UBYTE)
	'direction - 1-8 U,UR,R,DR,D,DL,LUL
	'numpixels - 1,2,4,8,16,32,64
	'scrollattributes - 0-1
	OUT LOKEYULAI_DATAPORT,direction
	OUT LOKEYULAI_DATAPORT,numpixels
	OUT LOKEYULAI_DATAPORT,scrollattributes
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_SCROLL
end sub

sub LOKEYULA_Roll(direction as UBYTE, numpixels as UBYTE,scrollattributes as UBYTE)
	'direction - 1-8 U,UR,R,DR,D,DL,LUL
	'numpixels - 1,2,4,8,16,32,64
	'scrollattributes - 0-1
	OUT LOKEYULAI_DATAPORT,direction
	OUT LOKEYULAI_DATAPORT,numpixels
	OUT LOKEYULAI_DATAPORT,scrollattributes
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_ROLL
end sub

sub LOKEYULA_PrintChar(x as UBYTE, y as UBYTE,character as UBYTE, mask as UBYTE)
	OUT LOKEYULAI_DATAPORT,x
	OUT LOKEYULAI_DATAPORT,y
	OUT LOKEYULAI_DATAPORT,character
	OUT LOKEYULAI_DATAPORT,mask
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_PRINTCHAR
end sub

sub LOKEYULA_PrintLine(x as UBYTE, y as UBYTE,character as UBYTE, mask as UBYTE)
	OUT LOKEYULAI_DATAPORT,x
	OUT LOKEYULAI_DATAPORT,y
	OUT LOKEYULAI_DATAPORT,character
	OUT LOKEYULAI_DATAPORT,mask
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_PRINTLINE
end sub

sub LOKEYULA_SetCopperIntensity(index as UBYTE, indexvalue as UBYTE)
	OUT LOKEYULAI_DATAPORT,index
	OUT LOKEYULAI_DATAPORT,indexvalue
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_SETCOPPERINTENSITY
end sub

sub LOKEYULA_SetCopperIntensityRange(startindex as UBYTE, endindex as UBYTE, indexvalue as UBYTE)
	'Sets a copperlist range of values
	OUT LOKEYULAI_DATAPORT,startindex
	OUT LOKEYULAI_DATAPORT,endindex
	OUT LOKEYULAI_DATAPORT,indexvalue
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_SETCOPPERINTENSITYRANGE
end sub

sub LOKEYULA_CopperIntensityShift(amount as BYTE, value as UBYTE)
	'Shifts the copperlist by some amount (max 96) and sets the old range to value
	OUT LOKEYULAI_DATAPORT,amount
	OUT LOKEYULAI_DATAPORT,value
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_COPPERINTENSITYSHIFT
end sub
sub LOKEYULA_CopperIntensityRoll(amount as BYTE)
	'Rolls the copperlist by some amount (max 96)
	OUT LOKEYULAI_DATAPORT,amount
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_COPPERINTENSITYROLL
end sub

sub LOKEYULA_SetCopperPalette(index as UBYTE, indexvalue as UBYTE)
	OUT LOKEYULAI_DATAPORT,index
	OUT LOKEYULAI_DATAPORT,indexvalue
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_SETCOPPERPALETTE
end sub

sub LOKEYULA_SetCopperPaletteRange(startindex as UBYTE, endindex as UBYTE, indexvalue as UBYTE)
	'Sets a copperlist range of values
	OUT LOKEYULAI_DATAPORT,startindex
	OUT LOKEYULAI_DATAPORT,endindex
	OUT LOKEYULAI_DATAPORT,indexvalue
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_SETCOPPERPALETTERANGE
end sub

sub LOKEYULA_CopperPaletteShift(amount as BYTE, value as UBYTE)
	'Shifts the copperlist by some amount (max 96) and sets the old range to value
	OUT LOKEYULAI_DATAPORT,amount
	OUT LOKEYULAI_DATAPORT,value
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_COPPERPALETTESHIFT
end sub
sub LOKEYULA_CopperPaletteRoll(amount as BYTE)
	'Rolls the copperlist by some amount (max 96)
	OUT LOKEYULAI_DATAPORT,amount
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_COPPERPALETTEROLL
end sub

sub LOKEYULA_Blit(sx as UBYTE, sy as UBYTE,dx as UBYTE, dy as UBYTE,width as UINTEGER,height as UBYTE, sourcedest as UBYTE)
	OUT LOKEYULAI_DATAPORT,sx
	OUT LOKEYULAI_DATAPORT,sy
	OUT LOKEYULAI_DATAPORT,dx
	OUT LOKEYULAI_DATAPORT,dy
	OUT LOKEYULAI_DATAPORT,PEEK (@width)
	OUT LOKEYULAI_DATAPORT,PEEK (@width+1)
	OUT LOKEYULAI_DATAPORT,height
	OUT LOKEYULAI_DATAPORT,sourcedest
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_BLIT
end sub

sub LOKEYULA_BlitAttribute(sx as UBYTE, sy as UBYTE,dx as UBYTE, dy as UBYTE,width as UINTEGER,height as UBYTE, sourcedest as UBYTE)
	OUT LOKEYULAI_DATAPORT,sx
	OUT LOKEYULAI_DATAPORT,sy
	OUT LOKEYULAI_DATAPORT,dx
	OUT LOKEYULAI_DATAPORT,dy
	OUT LOKEYULAI_DATAPORT,PEEK (@width)
	OUT LOKEYULAI_DATAPORT,PEEK (@width+1)
	OUT LOKEYULAI_DATAPORT,height
	OUT LOKEYULAI_DATAPORT,sourcedest
	OUT LOKEYULAI_COMMANDPORT,LOKEYULAI_BLITATTRIBUTE
end sub